# Generated by Django 5.1.2 on 2024-10-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Fiction", "Fiction"),
                            ("Non-Fiction", "Non-Fiction"),
                            ("Fantasy", "Fantasy"),
                            ("Science Fiction", "Science Fiction"),
                            ("Mystery", "Mystery"),
                            ("Biography", "Biography"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Good", "Good"),
                            ("Acceptable", "Acceptable"),
                            ("Worn", "Worn"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[("Exchange", "Exchange"), ("Lend", "Lend")],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("book_picture", models.ImageField(upload_to="book_pictures/")),
            ],
        ),
    ]
