# Generated by Django 5.1.2 on 2024-10-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_date_added_book_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Fiction", "Fiction"),
                    ("Non-Fiction", "Non-Fiction"),
                    ("Fantasy", "Fantasy"),
                    ("Science Fiction", "Science Fiction"),
                    ("Biography", "Biography"),
                    ("Mystery", "Mystery"),
                    ("Romance", "Romance"),
                    ("Horror", "Horror"),
                    ("Self-Help", "Self-Help"),
                    ("Historical", "Historical"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
    ]
